version: '3'
x-base-image: &default-base-image # name for reference
  env_file: go.env
  image: golang:${GO_VARIANT:-1.19.0-bullseye}
  working_dir: $DOCKER_GOSRC/webserver
  environment:
    - HOST=$HOST
    - SERVERPORT=${SERVERPORT:-8000}
  volumes:
    - $GOSRC:$DOCKER_GOSRC
  ports:
    - ${SERVERPORT:-8000}:${SERVERPORT:-8000}
services:
  go-network-dev:
    << : *default-base-image
    container_name: go-network-dev
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: >       # rather command than entrypoint due to vscode container
      /bin/bash -c "
        go mod download &&
        go install &&
        bash
      "
  go-server:
    << : *default-base-image
    container_name: go-server
    entrypoint: bash -c
    command:
      - |
        go install .
        webserver
  build-wasm:
    image: asenger/wasm-builder:0.0.15
    environment:
      - CFD=backend/src/webserver/CFD.yaml
      - WWW=backend/src/webserver/frontend/public/static/js/CodeDistributor
      - PLUGINS=backend/src/codedistribution/plugins
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    entrypoint: wasmbuilder
    command: all
